name: Kotlin CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
        matrix:
          os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    
    - name: Build with Gradle
      run: ./gradlew build --warning-mode all
